version: 0.2
phases:
  pre_build:
    commands:
      - IMAGE_TAG=$(date '+%Y%m%d%H%M%S')
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} src/
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - docker images
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":web","imageUri":"%s"}]' "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      #- sed -i "s/IMAGE_PLACEHOLDER/$REPOSITORY_URI:$IMAGE_TAG/g" image.json
      - cat imagedefinitions.json
artifacts: 
    files:
        - imagedefinitions.json
    discard-paths: yes